//! Generated by the presentation crate's `bake/bake_arimo.py` — do
//! not edit. This is the simulation-side half of the baked face: the
//! per-glyph integer advances, and nothing else. Bitmaps live with
//! presentation; measurement is a pure integer sum and never sees
//! them.

use crate::Fixed;

/// ASCII range the advance table covers.
pub const TEXT_FIRST: u32 = 32;
pub const TEXT_LAST: u32 = 126;
/// The baked line height, in pixels.
pub const LINE_HEIGHT: u32 = 15;
/// Pen advances, indexed by `code - TEXT_FIRST`, in pixels.
pub const ADVANCES: [u8; 95] = [
    4, 4, 5, 7, 7, 12, 9, 2, 4, 4, 5, 8, 4, 4, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 4, 8, 8, 8,
    7, 13, 9, 9, 9, 9, 9, 8, 10, 9, 4, 7, 9, 7, 11, 9, 10, 9, 10, 9, 9, 8, 9, 9, 12, 9, 9, 8, 4, 4,
    4, 6, 7, 4, 7, 7, 7, 7, 7, 4, 7, 7, 3, 3, 7, 3, 11, 7, 7, 7, 7, 4, 7, 4, 7, 7, 9, 7, 7, 7, 4,
    3, 4, 8,
];

/// The advance of one character: its own for printable ASCII, the
/// question mark's for anything else — a stand-in the picture will
/// show as itself, so measurement and rendering agree about width.
#[must_use]
pub fn advance_of(character: char) -> u32 {
    let code = character as u32;
    let index = if (TEXT_FIRST..=TEXT_LAST).contains(&code) {
        code - TEXT_FIRST
    } else {
        u32::from(b'?') - TEXT_FIRST
    };
    u32::from(ADVANCES[index as usize])
}

/// The width of `text` at the baked size, as the solver's own
/// arithmetic: a pure integer sum of advances, bit-identical on every
/// target.
#[must_use]
pub fn measure(text: &str) -> Fixed {
    let mut total: i32 = 0;
    for character in text.chars() {
        let advance = i32::try_from(advance_of(character)).unwrap_or(i32::MAX);
        total = total.saturating_add(advance);
    }
    Fixed::from_int(total)
}
