# The one-time glyph bake: Arimo-Regular rasterized at a fixed pixel
# size into generated Rust sources. Run manually, never in a build:
# the outputs are committed, and this script plus the README beside it
# are the recipe that reproduces them.
#
#   python bake_arimo.py <path-to-Arimo-Regular.ttf>
#
# The face's identity is pinned by hash in the README; this script
# refuses any other bytes, so a re-bake against a drifted file fails
# before it writes a line.

import hashlib
import sys

from PIL import Image, ImageDraw, ImageFont

FACE_SHA256 = "a5cb71302ce735698dfc756943c5bbcfbcc734e117ad452ccb3cb036e07dbd36"
SIZE_PX = 13
FIRST = 32
LAST = 126
# The margin on each side of a glyph's advance box: room for bearings
# and antialiasing. One constant ties the canvas width, the draw
# offset, and the emitted BEARING together.
MARGIN = 2


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: python bake_arimo.py <path-to-Arimo-Regular.ttf>")
    face_path = sys.argv[1]
    face_bytes = open(face_path, "rb").read()
    digest = hashlib.sha256(face_bytes).hexdigest()
    if digest != FACE_SHA256:
        raise SystemExit(
            f"refusing to bake: the face at {face_path} hashes to {digest}, "
            f"not the pinned {FACE_SHA256}"
        )

    font = ImageFont.truetype(face_path, SIZE_PX)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = max(0, round(font.getlength(ch)))
        if advance > 255:
            raise SystemExit(f"glyph {code} advances {advance}px; the table is u8")
        # Render the glyph alone on a canvas tall enough for the whole
        # line, anchored at the baseline the metrics give, so every
        # glyph shares one vertical coordinate system.
        canvas = Image.new("L", (advance + 2 * MARGIN, line_height), 0)
        draw = ImageDraw.Draw(canvas)
        draw.text((MARGIN, 0), ch, fill=255, font=font)
        width = canvas.width
        glyphs.append((code, advance, width, canvas))

    strip_width = sum(width for (_, _, width, _) in glyphs)
    strip = Image.new("L", (strip_width, line_height), 0)
    offsets = []
    x = 0
    for code, advance, width, canvas in glyphs:
        strip.paste(canvas, (x, 0))
        offsets.append((code, x, width, advance))
        x += width

    alpha = strip.tobytes()
    strip_hash = hashlib.sha256(alpha).hexdigest()

    write_glyphs_rs(offsets, alpha, strip_width, line_height, strip_hash)
    write_text_rs(offsets, line_height)
    print(f"strip {strip_width}x{line_height}, {len(alpha)} alpha bytes")
    print(f"strip sha256 {strip_hash}")


def write_glyphs_rs(offsets, alpha, strip_width, line_height, strip_hash) -> None:
    rows = []
    for code, x, width, advance in offsets:
        rows.append(f"    Glyph {{ x: {x}, width: {width}, advance: {advance} }},")
    table = "\n".join(rows)
    packed = ", ".join(str(b) for b in alpha)
    body = f'''//! Generated by `bake/bake_arimo.py` — do not edit. The recipe and
//! the face's pinned identity live in `bake/README.md`; the strip's
//! own content hash is {strip_hash}.

/// One baked glyph: where its column starts in the strip, how wide
/// its bitmap is, and how far the pen advances after it.
#[derive(Clone, Copy, Debug)]
pub struct Glyph {{
    pub x: u32,
    pub width: u32,
    pub advance: u32,
}}

/// The strip holds ASCII {FIRST}..={LAST}, one line-height tall.
/// Every glyph bitmap carries this margin on each side of its advance
/// box, room for antialiasing and bearing overhang; a renderer places
/// the bitmap at `pen - BEARING` so the ink centres on the advance.
pub const BEARING: u32 = {MARGIN};
pub const GLYPH_FIRST: u32 = {FIRST};
pub const GLYPH_LAST: u32 = {LAST};
pub const STRIP_WIDTH: u32 = {strip_width};
pub const LINE_HEIGHT: u32 = {line_height};

/// Per-glyph placement, indexed by `code - GLYPH_FIRST`.
pub const GLYPHS: [Glyph; {len(offsets)}] = [
{table}
];

/// The strip's alpha bytes, row-major, one byte per texel.
pub const STRIP_ALPHA: [u8; {len(alpha)}] = [{packed}];
'''
    open("../src/glyphs.rs", "w", newline="\n", encoding="utf-8").write(body)


def write_text_rs(offsets, line_height) -> None:
    advances = ", ".join(str(advance) for (_, _, _, advance) in offsets)
    body = f'''//! Generated by the presentation crate's `bake/bake_arimo.py` — do
//! not edit. This is the simulation-side half of the baked face: the
//! per-glyph integer advances, and nothing else. Bitmaps live with
//! presentation; measurement is a pure integer sum and never sees
//! them.

use crate::Fixed;

/// ASCII range the advance table covers.
pub const TEXT_FIRST: u32 = {FIRST};
pub const TEXT_LAST: u32 = {LAST};
/// The baked line height, in pixels.
pub const LINE_HEIGHT: u32 = {line_height};
/// Pen advances, indexed by `code - TEXT_FIRST`, in pixels.
pub const ADVANCES: [u8; {len(offsets)}] = [{advances}];

/// The advance of one character: its own for printable ASCII, the
/// question mark's for anything else — a stand-in the picture will
/// show as itself, so measurement and rendering agree about width.
#[must_use]
pub fn advance_of(character: char) -> u32 {{
    let code = character as u32;
    let index = if (TEXT_FIRST..=TEXT_LAST).contains(&code) {{
        code - TEXT_FIRST
    }} else {{
        u32::from(b'?') - TEXT_FIRST
    }};
    u32::from(ADVANCES[index as usize])
}}

/// The width of `text` at the baked size, as the solver's own
/// arithmetic: a pure integer sum of advances, bit-identical on every
/// target.
#[must_use]
pub fn measure(text: &str) -> Fixed {{
    let mut total: i32 = 0;
    for character in text.chars() {{
        let advance = i32::try_from(advance_of(character)).unwrap_or(i32::MAX);
        total = total.saturating_add(advance);
    }}
    Fixed::from_int(total)
}}
'''
    open("../../ui/src/text.rs", "w", newline="\n", encoding="utf-8").write(body)


if __name__ == "__main__":
    main()
