//! Wiring the game's sounds to a device.
//!
//! Everything here is the four lines the engine deliberately refuses to
//! write for anyone: the audio crate mixes and the platform crate
//! carries, and neither names the other, so the sample is where they
//! meet. That is what keeps both halves independently removable.
//!
//! Compiled only with the `audio` feature, which requires `window` —
//! the headless runs are the ones whose output is compared byte for
//! byte, and they stay silent by construction rather than by flag.

use renew_audio::{MixerConfig, SoundId, mixer, wav};
use renew_platform::audio::{AudioDevice, AudioOutput};

use crate::sound::TickSounds;

/// The three sounds, generated by the committed example beside them
/// (`samples/glide/sounds/README.md` carries the record). Embedded
/// rather than read at runtime: the game is one binary, and a sound
/// that can go missing is a crash waiting for a working directory.
static FLAP: &[u8] = include_bytes!("../sounds/flap.wav");
static SCORE: &[u8] = include_bytes!("../sounds/score.wav");
static DEATH: &[u8] = include_bytes!("../sounds/death.wav");

/// The live sound half of a run.
pub struct Audio {
    handle: renew_audio::MixerHandle,
    output: AudioOutput,
    flap: SoundId,
    score: SoundId,
    death: SoundId,
}

impl Audio {
    /// Open a device, load the three sounds, and start the stream.
    ///
    /// `Err` carries the human reason this machine cannot play — no
    /// device, no backend, a format the mixer does not speak. The
    /// caller says it once and the game goes on in silence; a player
    /// without a sound card is not a failed run.
    ///
    /// The order is the one the seam requires: open the device, ask it
    /// what shape its buffers are, build the mixer to that shape, load
    /// every sound (converting each once), and only then hand the mixer
    /// to the callback. Nothing expensive can happen after that point,
    /// because after that point it happens on the audio thread.
    pub fn open() -> Result<Self, String> {
        let device = AudioDevice::open().map_err(|error| error.to_string())?;
        let config = device.config();
        let (handle, mut mix) = mixer(MixerConfig::new(config.channels, config.sample_rate));
        let flap = load(&mut mix, FLAP)?;
        let score = load(&mut mix, SCORE)?;
        let death = load(&mut mix, DEATH)?;
        let output = device
            .start(move |out| mix.fill(out))
            .map_err(|error| error.to_string())?;
        Ok(Self {
            handle,
            output,
            flap,
            score,
            death,
        })
    }

    /// Ask for whatever this tick produced.
    ///
    /// A refused command — the ring full — is dropped rather than
    /// retried: the alternative is a game thread waiting on an audio
    /// thread, and a missing blip is cheaper than a missed frame.
    pub fn play(&self, sounds: TickSounds) {
        if sounds.flap {
            let _ = self.handle.play(self.flap);
        }
        for _ in 0..sounds.scores {
            let _ = self.handle.play(self.score);
        }
        if sounds.death {
            let _ = self.handle.play(self.death);
        }
    }

    /// Whether the stream is still alive. A device that died mid-run
    /// leaves the game playable and the summary honest.
    #[must_use]
    pub fn healthy(&self) -> bool {
        self.output.healthy()
    }
}

/// Parse and load one embedded sound, reporting rather than panicking:
/// these bytes are committed beside the code, so a refusal here means
/// the reader's accepted set moved and the sounds were not regenerated
/// — worth saying out loud, not worth killing a run over.
fn load(mix: &mut renew_audio::Mixer, bytes: &'static [u8]) -> Result<SoundId, String> {
    let sound =
        wav::parse(bytes).map_err(|error| format!("a committed sound was refused: {error}"))?;
    Ok(mix.load(&sound))
}
