//! The WAV reader, against bytes nobody wrote on purpose.
//!
//! `parse` reads a sound file the engine did not encode and must not
//! trust. It answers with a borrowed view of the samples or a refusal
//! naming the field that was wrong; a panic, a hang, or a read past the
//! end are not answers, and this target exists to look for those.
//!
//! The suite beside the reader already asserts the same property over
//! generated bytes with a fixed budget. What this adds is coverage
//! guidance — the fuzzer keeps the inputs that reach new branches, so it
//! works its way past the magic number and the container header into the
//! chunk walk, where the padding, extension and skip paths live and where
//! uniform random bytes essentially never land.

#![no_main]

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    // The result is deliberately discarded: the property under test is
    // that the call returns at all. Which fields it returns, and which
    // refusal it names, are the round-trip and refusal suites' business,
    // and asserting on them here would fail the corpus rather than the
    // code — a malformed input is a legitimate corpus entry.
    let _ = renew_audio::wav::parse(data);
});
